### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by CrayRayy** [gucci-on-fleek/lockdown-browser#1]
Hi man, 

Great work! 
Is there any way to use this bypass for LDB on a Mac?

Cheers

**Comment by gucci-on-fleek** [comment]
Kind of. I don't have a Mac so this program isn't designed for one, but you should be able to virtualize a Windows system and run it there. There are two options (but neither are easy):

1. (Nested Virtualization) You can install Windows in a VM, then run the whole program in there.
    
    You'd need to install a hypervisor on the Mac (probably VirtualBox or Parallels, but VMware should work too). Then you could install Windows 10 Pro. Now you just have a plain Windows system, so running this repo should behave identically to a standard Windows PC.

    You'll need to have nested virtualization enabled ([VirtualBox](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html), [Parallels](https://kb.parallels.com/116239)) which is often a little janky.

2. (Direct Virtualization) You can try running everything directly in 1 VM, without using _Windows Sandbox_.

    This method would have the best performance, but you might need to do some extra work yourself. Instead building in the outer VM and running in the inner _Windows Sandbox_ as with the previous method, you would build and run everything in the outer VirtualBox/Parallels VM. 

    This tool has only been tested with hiding the traces from _Sandbox_ though. The _Sandbox_ doesn't visualize very much hardware, so there aren't very many traces to hide. VirtualBox and Parallels virtualize a fair bit more, so you _may_ need to make some modifications and hide a bit more. Everything might just work with no modifications though, so you'll need to test to find out. Don't install any "Guest Additions" though, since that will make it way more obvious that you're using a VM.

All of this assumes that you're running an Intel Mac. If you're using Apple Silicon/M1, everything gets way more complicated.

I'd personally recommend Method 1 with VirtualBox since it should require the fewest modifications. You can download [VirtualBox here](https://www.virtualbox.org/wiki/Downloads) and [a Windows 10 VM (includes VS!) here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/). Be warned: this will take most of a day to set up, and will probably take up around 20–30 GB of disk space.
