### ISSUE TITLE
Lockdown detects alt tabbing

### ISSUE THREAD

**Issue by mayed505** [gucci-on-fleek/lockdown-browser#11]
Hi there,

As of this week’s update, if you have the windows sandbox minimized and opening it up again, it detects that and sends to the instructor about it.

Even if you for example open Google chrome over the windows sandbox, then minimize Google chrome, a warning would pop up. If you do it again, the lockdown closes down.

The same thing does for using on a touch screen as well.

**Comment by gucci-on-fleek** [comment]
I don't have a copy of the _Browser_ to test right now, but I have a pretty good guess as to what's going on.

Minimizing/restoring the Sandbox window is probably sending a [`WM_DISPLAYCHANGE`](https://learn.microsoft.com/en-us/windows/win32/gdi/wm-displaychange) message (or something similar) to the _Browser_. I'm guessing that moving Chrome over the Sandbox window is sending a [`WM_WINDOWPOSITIONCHANGED`](https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-windowposchanged) message (or something similar).

There's a pretty good change that you can block the `WM_WINDOWPOSITIONCHANGED` message by setting [`ProtectedClient` in the `.wsb` files](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file#protected-client) (untested). To block the `WM_DISPLAYCHANGE` message, you'd probably need to install a [message hook](https://learn.microsoft.com/en-us/windows/win32/winmsg/about-hooks). 

As a more temporary solution, you'd probably be fine if you opened Chrome on one monitor and the Sandbox on a separate monitor. You would probably also be fine if you "tiled" Chrome and the Sandbox beside each other and never change either of their positions once the _Browser_ is open.

If if there's a really simple fix to this, then I *might* have time in the next month; otherwise, your best bet would be to submit a PR, which I would have no problem reviewing and merging.
