### ISSUE TITLE
Access to pass denied in Windows 11

### ISSUE THREAD

**Issue by ShirowLeBG** [gucci-on-fleek/lockdown-browser#14]
Hello !

When I try to open the Sandbox.wsb, it seems like the powershell script fail somewhere as the installation program doesn't start. I tried to launch it manually and I find this error :

![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/61913454/d1c8012f-d7ca-4bce-892e-364019e808d3)

Do you know how to fix that (and if possible, automatically at each launch) ?

Thanks 👍

**Comment by gucci-on-fleek** [comment]
Sorry, looks like I somehow missed seeing this issue when you posted it.

The issue here is that `icacls` is failing for some reason, although I'm not too sure why.

You could maybe try replacing

https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/runtime_directory/sandbox_run.ps1#L23

with

```powershell
icacls $vmcompute_path /grant "*S-1-1-0:(D)"
```

although I have no idea if this will actually fix anything.
