### ISSUE TITLE
I get the terminal services error when opening manually again from my organisations link

### ISSUE THREAD

**Issue by rarehusayn** [gucci-on-fleek/lockdown-browser#22]

**Comment by gucci-on-fleek** [comment]
From [the main page](https://github.com/gucci-on-fleek/lockdown-browser#you-get-a-terminal-services-error-message):

> ### You get a “Terminal Services” error message
> 
> If the _Lockdown Browser_ fails to launch, **do not double-click** the file on the VM's desktop. Instead, open a PowerShell prompt inside the VM and run:
> 
> ```powershell
> cd C:\Users\WDAGUtilityAccount\Desktop\runtime_directory\
> .\withdll.exe /d:GetSystemMetrics-Hook.dll "C:\Program Files (x86)\Respondus\LockDown Browser\LockDownBrowser.exe"
> ```
> 
> Of course, this is usually symptomatic of another issue, so please make sure that you have followed all the earlier instructions.
> 


If this isn't the issue, then I'll need some more details.

**Comment by huzzxin** [comment]
I tried that and it worked, but the lockdown browser of my organisation does not allow you to use the browser for searching and opening up the link you have to open an RLDB link on firefox/chrome that opens up the lockdown browser with some set parameters that make it go to that site link. I tried to get exactly what was in the link that opens it up but it seemed like it was all encrypted, however once you finish a test you can actually go to google or browse other sites in the browser because it redirects you to the organisation homepage which means the browser is definitely capable of opening webpages it just has to open the webpage on startup.

**Comment by gucci-on-fleek** [comment]
This should be supported, see #5 and f73c3f2. Usually the procedure to use this is to open the _Sandbox_, wait for the _Browser_ to open, then close the _Browser_. Then still **inside** the _Sandbox_, open Edge, log in to your school's system, then click whatever link to launch the _Browser_. 

I've never personally tested any of this myself, but it seems to have worked for other people in the past. If this isn't working, then let me know and I'll try and figure something out.

**Comment by gucci-on-fleek** [comment]
Hopefully fixed? If not, feel free to reopen.
