### ISSUE TITLE
webcam and microphone not working for macbook pro running windows 10 partition

### ISSUE THREAD

**Issue by HaLTic** [gucci-on-fleek/lockdown-browser#33]
installed windows 10 pro using bootcamp, everything runs normally but the camera doesn't work and gives an error "NotReadableError: Could not start video source".

everything is up to date, 
camera works outside of sandbox
for some reason windows sanbox does not exist in 
gpedit `Computer Configuration\Administrative Templates\Windows Components\Windows Sandbox`
nor 
regedit `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Sandbox.`

windows 10 pro, version: 22H2, OS build: 19045.3448

**Comment by gucci-on-fleek** [comment]
Ok, so silly question I know, but you are using `Sandbox-with-Microphone-Camera.wsb` and _not_ the regular `Sandbox.wsb`, right? Because you can only use the camera with if you run the `Sandbox-with-Microphone-Camera.wsb` file.

If you're sure that you're using the right file, then try testing the camera in the _Sandbox_ without using the _Browser_:

> <sup>_Originally posted by @gucci-on-fleek in https://github.com/gucci-on-fleek/lockdown-browser/issues/27#issuecomment-1698541646_</sup>
> Is the standard Windows "Camera" app available in the _Sandbox_? If so, what happens when you open it? Does it detect the webcam?
> 
> If the app isn't preinstalled in the _Sandbox_ for some reason, try testing the camera with this link
> 
> > [`https://mozilla.github.io/webrtc-landing/gum_test.html`](https://mozilla.github.io/webrtc-landing/gum_test.html)
> 
> with Edge (inside the _Sandbox_). Does that work?

If that doesn't work maybe try installing/updating the Bootcamp drivers on the host system. I think that [this is the latest download](https://support.apple.com/kb/DL1831?viewlocale=en_US&locale=en_US), but I've never used a Mac, so you'll know more about this than I do.

Next, maybe try comparing the Device Manager camera results between the host and the _Sandbox_. Maybe there'll be some hint as to what's going on in there.

I doubt that this will do anything at all, but you could try installing the [Apple camera drivers](https://support.apple.com/kb/DL1831?viewlocale=en_US&locale=en_US) _inside_ the _Sandbox_. I'd be surprised if that worked though.

> for some reason windows sanbox does not exist in
> gpedit `Computer Configuration\Administrative Templates\Windows Components\Windows Sandbox`
> nor
> regedit `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Sandbox`.

I don't think that should matter, so long as you're able to launch the _Sandbox_ at all (which it sounds like you can).

> windows 10 pro, version: 22H2, OS build: 19045.3448

That version looks fine to me, but installing any updates (if they're available) _might_ fix something.

**Comment by gucci-on-fleek** [comment]
It's been a little while and I haven't seen any new replies, so hopefully this is fixed now? If not, feel free to add a new comment or reopen the issue.
