### ISSUE TITLE
Update server is not supplying update information, or the connection to Update server is blocked. Please try again later.

### ISSUE THREAD

**Issue by 7echLife** [gucci-on-fleek/lockdown-browser#58]
I followed all of the steps, and no matter what I do Lockdown Browser will not open correctly because the update server cannot be accessed. It would also say the software is installed in Temp folder quickly before the notification window closes itself for a split second. I do have portmaster and vpn on, and turning those off does not remedy the issue. I only have until Wednesday to fix this issue, so please help me ASAP. This is really urgent.

![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/54084841/d7a79db1-51e8-48f9-93aa-5c72920d40ba)

**Comment by 7echLife** [comment]
Here is what I was talking about with the software installed in the temp folder under windows, but at the same time it is also installed in its normal location. ![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/54084841/c53b6f3d-fbec-49c2-8ee2-2c5eda3f579b)

![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/54084841/249411d9-fe12-4933-8e74-624397a13093)

![image](https://github.com/gucci-on-fleek/lockdown-browser/assets/54084841/862012ab-4cfe-4f2b-8dbd-61ce41a7094a)

This is annoying and shouldn't happen.

**Comment by gucci-on-fleek** [comment]
> It would also say the software is installed in Temp folder quickly before the notification window closes itself for a split second.

> the software installed in the temp folder under windows, but at the same time it is also installed in its normal location. 

This is the expected behaviour. You can see it in the “Demo Video” on [the main page](https://github.com/gucci-on-fleek/lockdown-browser) at `1:25`.

The “normal” way to install the _Lockdown Browser_ is to double-click on the installer file, then click through a bunch of buttons in the install wizard. This isn't really amenable to automation, so we need to convince the installer to do an “unattended” installation by passing a bunch of flags to the installer file. But the installer runs in two steps: step 1 unpacks the files into the `temp` folder, then step 2 runs a _different_ program that actually installs the _Browser_. But it's _impossible_ to run step 1 without it showing that dialog and pausing until you click “OK”, so the script uses a workaround:

https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/runtime_directory/sandbox_run.ps1#L26-L35

It's a very inelegant solution, but it's the only way that I could make it work. You can try lowering the `sleep` values if you want the dialog to close quicker, but lowering them too much will make the installation fail.

> I do have portmaster and vpn on, and turning those off does not remedy the issue

Those are almost certainly the issue, so I'd recommend turning both of those (and any other firewall stuff) _completely_ off, reboot your computer, then try again. 

If that doesn't work, then try the instructions in https://github.com/gucci-on-fleek/lockdown-browser/issues/49#issuecomment-1937011554

> Is your date and time correct? If it is, try opening each of these links in a regular browser outside of the _Sandbox_:
> 
> ```text
> https://server-profiles-respondus-com.s3-external-1.amazonaws.com
> https://static-public-downloads-cloud.respondus.com
> https://www.respondus.com
> https://help-center-respondus-com.s3.amazonaws.com
> https://smc-service-cloud.respondus2.com
> ```
> 
> It's fine if you get an “Access Denied” message, but if you get a “page not found” or “connection failure” message for **any** of those 5 links, then that suggests that you have a firewall issue of some sort. How you would fix that would depend on where the firewall is, but regardless, it wouldn't be a bug/issue with this project.
> 
> If all of those links work and your clock is correct, then I'm not sure what the issue is. Maybe try adding
> 
> ```xml
> <Networking>Enable</Networking>
> ```
> 
> to `Sandbox.wsb`, between `<configuration>`/`</configuration>`:
> 
> https://github.com/gucci-on-fleek/lockdown-browser/blob/7248e2999c70bd913345483873cfc8e623bc99a0/src/Sandbox.wsb#L6-L19
> 
> _([source](https://learn.microsoft.com/en-us/windows/security/application-security/application-isolation/windows-sandbox/windows-sandbox-configure-using-wsb-file#networking))_
> 
> Make sure to fully-rebuild the files after changing that.

**Comment by 7echLife** [comment]
Okay, I am back and did everything you recommended. It worked. I want to thank you so much for your work. You are doing God's work for privacy. Sadly the VPN and Portmaster has to be off, but the Browser is in a Sandbox environment. Godspeed and have a blessed day, you deserve it.
