### ISSUE TITLE
Can you help me because I don't know where to start and I have a lockdown browser Lab OEM and if you help me and it works, I can pay you.

### ISSUE THREAD

**Issue by Martin0131** [gucci-on-fleek/lockdown-browser#63]
Can you help me because I don't know where to start and I have a lockdown browser Lab OEM and if you help me and it works, I can pay you.

**Comment by gucci-on-fleek** [comment]
The [main page](https://github.com/gucci-on-fleek/lockdown-browser#system-requirements) has some pretty good instructions; #24 goes into a little more detail if you're struggling.

But I'd check #65 and https://github.com/gucci-on-fleek/lockdown-browser/discussions/53#discussioncomment-8909229 before trying this since many people have been having issues lately.

I'll close this for now, but please feel free to add more comments if you have any other questions.
