### ISSUE TITLE
HELP HELP HELP

### ISSUE THREAD

**Issue by whatiswrongwithdota** [gucci-on-fleek/lockdown-browser#66]
why would u ban a player who reconnected while hero pick? how to play without getting reported by toxic players when i dont even chat? does this happen only in sea server? why is d2 becoming so toxic that we cant eVen reach the devs for help?

**Comment by kiwi08522** [comment]
I think you meant to post this somewhere else?

**Comment by gucci-on-fleek** [comment]
This project has nothing to do with Destiny (or Bungie or video games in general), so I'm not sure why you're posting this here. Actually, I'm not sure how you even _found_ this project, or why you made an new GitHub account (that references DOTA?) just to post this here. And even assuming that I was somehow affiliated with Bungie (which is **emphatically not true**), this wouldn't even be an actionable report since it's missing things like your game version, username, details, and so on (which again, wouldn't actually help since I'm a random Canadian university student who spends most of his time working on [obscure typesetting software from the 80's](https://tug.org/~mseven/)).
